<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\D6_UNIFOR_ACHADOS_PERDIDOS_API.Domain\D6_UNIFOR_ACHADOS_PERDIDOS_API.Domain.csproj" />
    <ProjectReference Include="..\D6_UNIFOR_ACHADOS_PERDIDOS_API.Application\D6_UNIFOR_ACHADOS_PERDIDOS_API.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
